version: '3'

services:
  database:
    image: mongo:3.6-xenial
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root+passwd
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
  
  app:
    build:
      context: .
      args:
        VUE_APP_ROOT_API: /api
    image: carlospavanetti/totvs-fullstack-challenge
    environment:
      MONGO_URL: mongodb://root:root+passwd@database:27017/?poolSize=20&w=majority
      MONGO_DATABASE: totvs-challenge
    ports:
      - 8888:8000
    depends_on:
      - database

volumes:
  mongo_data:
