version: '3'

services:
  database:
    image: mongo:3.6-xenial
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root+passwd
    volumes:
      - mongo_data:/data/db
  
  app:
    build: .
    image: carlospavanetti/totvs-fullstack-challenge
    environment:
      MONGO_URL: mongodb://root:root+passwd@database:27017/?poolSize=20&w=majority
      MONGO_DATABASE: totvs-challenge
      VUE_APP_ROOT_API: /api
    ports:
      - 8888:8000

volumes:
  mongo_data:
